# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-03 05:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='dish',
        ),
        migrations.AddField(
            model_name='dish',
            name='composition',
            field=models.TextField(default=datetime.datetime(2016, 9, 3, 5, 7, 52, 485037, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
